# Generated by Django 5.0.7 on 2024-10-12 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('organizerID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('organizerName', models.TextField(max_length=100)),
                ('organizerType', models.CharField(max_length=10)),
                ('organizerContactNum', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('userFullName', models.TextField(max_length=80)),
                ('username', models.TextField(max_length=50)),
                ('userPassword', models.TextField(max_length=50)),
                ('userContactNum', models.CharField(max_length=11)),
                ('userEmail', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('campaignID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('campaignName', models.TextField(max_length=100)),
                ('campaignDesc', models.TextField(max_length=9)),
                ('targetAmount_RM', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numOfDonors', models.IntegerField(default=0)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('organizerName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KPMBFundHub.organizer')),
            ],
        ),
    ]
