# Generated by Django 5.0.7 on 2024-10-12 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KPMBFundHub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('donationID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('amountDonated', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paymentMethod', models.TextField(max_length=20)),
                ('dateNtime', models.DateTimeField()),
                ('paymentStatus', models.TextField(default='Success', max_length=50)),
                ('campaignName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KPMBFundHub.campaign')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KPMBFundHub.user')),
            ],
        ),
    ]
