# Generated by Django 5.0.7 on 2024-10-13 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KPMBFundHub', '0002_donation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizer',
            name='organizerType',
        ),
        migrations.AddField(
            model_name='organizer',
            name='organizationName',
            field=models.TextField(default='organization01', max_length=100),
        ),
        migrations.AddField(
            model_name='organizer',
            name='organizerPassword',
            field=models.TextField(default='organizer123', max_length=50),
        ),
    ]
