# Generated by Django 5.0.7 on 2024-10-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KPMBFundHub', '0003_remove_organizer_organizertype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='organizationName',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='organizerPassword',
            field=models.TextField(max_length=50),
        ),
    ]
