# Generated by Django 5.0.7 on 2024-10-13 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KPMBFundHub', '0004_alter_organizer_organizationname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizer',
            name='organizationName',
        ),
        migrations.AddField(
            model_name='organizer',
            name='organizerUsername',
            field=models.TextField(default='org123', max_length=50),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='organizerName',
            field=models.TextField(max_length=80),
        ),
    ]
