# Generated by Django 5.0.7 on 2024-10-14 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KPMBFundHub', '0006_alter_organizer_organizerusername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='organizerName',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='campaignName',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='username',
        ),
        migrations.DeleteModel(
            name='Organizer',
        ),
        migrations.DeleteModel(
            name='Campaign',
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
