# Generated by Django 5.0.7 on 2024-10-15 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('KPMBFundHub', '0007_remove_campaign_organizername_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('orgID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('orgName', models.TextField(max_length=50)),
                ('orgUsername', models.TextField(max_length=50)),
                ('orgPassword', models.TextField(max_length=50)),
                ('orgContactNum', models.TextField(max_length=50)),
                ('orgDesc', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('userFirstName', models.TextField(max_length=50)),
                ('userLastname', models.TextField(max_length=50)),
                ('username', models.TextField(max_length=50)),
                ('userPassword', models.TextField(max_length=50)),
                ('userContactNum', models.CharField(max_length=11)),
                ('userEmail', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('campaignID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('campaignName', models.TextField(max_length=50)),
                ('campaignDesc', models.TextField(max_length=200)),
                ('targetAmount_RM', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numOfDonors', models.IntegerField(default=0)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('orgName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KPMBFundHub.organizer')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('donationID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('amountDonated_RM', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paymentMethod', models.TextField(max_length=20)),
                ('dateNtime', models.DateTimeField()),
                ('paymentStatus', models.TextField(default='Success', max_length=50)),
                ('campaignID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KPMBFundHub.campaign')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KPMBFundHub.user')),
            ],
        ),
    ]
