# Generated by Django 5.0.7 on 2024-10-15 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KPMBFundHub', '0008_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userLastname',
            new_name='userLastName',
        ),
    ]
