# Generated by Django 5.0.7 on 2024-10-15 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KPMBFundHub', '0009_rename_userlastname_user_userlastname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='orgName',
        ),
        migrations.AddField(
            model_name='campaign',
            name='orgID',
            field=models.ForeignKey(default='O001', on_delete=django.db.models.deletion.CASCADE, to='KPMBFundHub.organizer'),
        ),
    ]
