# Generated by Django 5.0.7 on 2024-10-15 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KPMBFundHub', '0010_remove_campaign_orgname_campaign_orgid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='campaignDesc',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='orgDesc',
            field=models.TextField(max_length=500),
        ),
    ]
