# Generated by Django 5.0.7 on 2024-10-15 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KPMBFundHub', '0011_alter_campaign_campaigndesc_alter_organizer_orgdesc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='orgID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KPMBFundHub.organizer'),
        ),
    ]
