# Generated by Django 5.0.7 on 2024-10-17 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KPMBFundHub', '0012_alter_campaign_orgid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizer',
            name='orgUsername',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
