# Generated by Django 5.0.7 on 2024-10-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KPMBFundHub', '0013_remove_organizer_orgusername_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.TextField(default='Ali', max_length=20),
        ),
    ]
